# NEOS DEVELOPMENT ENVIRONMENT
#
# For instructions how to use docker-compose, see
# https://docs.neos.io/cms/installation-development-setup/docker-and-docker-compose-setup#docker-compose-cheat-sheet
version: '3.5'
services:
  # Neos CMS
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/var/www
    networks:
      - internal-network

  web:
    image: nginx:alpine
    restart: always
    tty: true
    environment:
      VIRTUAL_HOST: khg-tanzkreis.fleigm.de,www.khg-tanzkreis.fleigm.de
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: khg-tanzkreis.fleigm.de,www.khg-tanzkreis.fleigm.de
      LETSENCRYPT_EMAIL: admin@fleigm.de
    expose:
      - 80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internal-network
      - nginx-proxy

#Docker Networks
networks:
  internal-network:
    driver: bridge
  nginx-proxy:
    external: true
    name: nginx-proxy
